spring:
  datasource:
    url: jdbc:postgresql://order-db:5432/${DB_NAME:orderservice}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

server:
  port: 8082

user-service:
  url: ${USER_SERVICE_URL:http://userservice:8080}
